"""add image_file column

Revision ID: 23faa3967597
Revises: 9208e56e820d
Create Date: 2025-11-02 13:47:10.063491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23faa3967597'
down_revision = '9208e56e820d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
